### ISSUE TITLE
Requisitos do Sistema

### ISSUE THREAD

**Issue by WhoisBsa** [WhoisBsa/utodo#1]
- [x]  O sistema deve ser responsivo e possuir tratamento do design via CSS e JavaScript.
- [x] O sistema precisa ter banco de dados.
- [x] O sistema deve possuir cadastro de usuários e um mecanismo de login e senha.
- [x] O sistema precisa fornecer pelo menos 1 CRUD completo de alguma tabela do banco (Inserção, alteração, remoção e seleção), que não seja a dos usuários.
- [x] As inserções, alterações e remoções obviamente devem ser seletivas (aplicadas em algum objeto específico), porém o sistema deve ter pelo menos 1 seleção seletiva (mostrar algum dado específico caso o usuário queira), que não seja a dos usuários.
- [x] O sistema deve possuir algum tipo de associação muitos para muitos no banco de dados.
- [x] O sistema precisa ter algum tipo de manipulação de diretórios e arquivos.
- [x] O sistema precisa ter tratamento de exceções.
- [x] O sistema deve ter um nome e uma logomarca exclusiva.
- [x] O sistema deve possuir pelo menos uma galeria de fotos.

**Comment by hemilioaraujo** [comment]
# Pendências do BD

- [x] Select de todos ToDos do usuário
- [x] Select de todos usuários relacionados a ToDo
- [x] Select de todos usuários do sistema
- [x] Select para login retornando o id, name e pass do usuário
- [x] Inserir ToDo
- [x] Inserir Usuário
- [x] Excluir ToDo
- [x] Atualizar ToDo

**Comment by hemilioaraujo** [comment]
> - [x]  O sistema deve ser responsivo e possuir tratamento do design via CSS e JavaScript.
> - [x] O sistema precisa ter banco de dados.
> - [x] O sistema deve possuir cadastro de usuários e um mecanismo de login e senha.
> - [x] O sistema precisa fornecer pelo menos 1 CRUD completo de alguma tabela do banco (Inserção, alteração, remoção e seleção), que não seja a dos usuários.
> - [ ] As inserções, alterações e remoções obviamente devem ser seletivas (aplicadas em algum objeto específico), porém o sistema deve ter pelo menos 1 seleção seletiva (mostrar algum dado específico caso o usuário queira), que não seja a dos usuários.
> - [x] O sistema deve possuir algum tipo de associação muitos para muitos no banco de dados.
> - [ ] O sistema precisa ter algum tipo de manipulação de diretórios e arquivos.
> - [x] O sistema precisa ter tratamento de exceções.
> - [x] O sistema deve ter um nome e uma logomarca exclusiva.
> - [ ] O sistema deve possuir pelo menos uma galeria de fotos.
>
